version: '3.8'

services:
  agno_browser_sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: agno-browser-sandbox:latest 
    container_name: agno_browser_sandbox_container 
    ports:
      # API for AgnoBrowserToolkit (host:container)
      - "8004:8003"  # AgnoBrowserToolkit default host_port maps to browser_api.py port
      # VNC Web Access (noVNC)
      - "8005:6080"
      # Raw VNC Access
      - "8006:5901"
      # Static file server for /workspace
      - "8007:8080"
      # Chrome DevTools Protocol (optional, for debugging)
      - "9222:9222"
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD:-agnopass}
      - RESOLUTION=${RESOLUTION:-1024x768x24} # More common desktop resolution
      - RESOLUTION_WIDTH=${RESOLUTION_WIDTH:-1024}
      - RESOLUTION_HEIGHT=${RESOLUTION_HEIGHT:-764}
      - CHROME_PERSISTENT_SESSION=${CHROME_PERSISTENT_SESSION:-true} 
      - ANONYMIZED_TELEMETRY=false
      - CHROME_DEBUGGING_PORT=9222
      - TZ=America/New_York # Example: Common timezone
      - LANG=en_US.UTF-8    # Example: Common locale
      # Ensure this path is writable by the user running Chrome in the container
      - CHROME_USER_DATA_DIR=/app/browser_user_data 
    volumes:
      - ./workspace:/workspace 
      # Volume for persistent browser profile data
      - browser_user_data:/app/browser_user_data 
    restart: unless-stopped
    shm_size: '2gb' 
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined 
    tmpfs:
      - /tmp
    # Healthcheck commented out as per previous step, can be re-enabled later
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "5901"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

volumes:
  workspace:
  browser_user_data: # Named volume for browser profile